name: 🏴‍☠️ Отправка
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 9 1 * *"
  workflow_dispatch:
    inputs:
        Name:
            description: 🏗️ Отправка на сайт
            required: true
            default: '🏗️ Отправка на сайт'
jobs:
  build:
    name: 🎉 Развёртывание
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Получить последний код
      uses: actions/checkout@v4
    
    - name: 📂 Заливка файлов
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /
        local-dir: ./site/
        state-name: .status.json
    - name: 💯 Удаляем статус файл и кэш сайта
      uses: StephanThierry/ftp-delete-action@v2.1
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remoteFiles: ".status.json;assets/cache/docid_*.php"
        workingDir: /
        ignoreSSL: 1
