name: 🚀 Deploy website
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
        Name:
            description: 🚀 Deploy website
            required: true
            default: '🚀 Deploy website'
jobs:
  build:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /
        local-dir: ./site/
        state-name: .status.json
    - name: 💯 Remove Status
      uses: StephanThierry/ftp-delete-action@v2.1
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remoteFiles: ".status.json;assets/cache/docid_*.php"
        workingDir: /
        ignoreSSL: 1
