name: Новости компании
on:
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-readme-with-blog:
    name: 🎯 Обновление README.md
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Проверка... ☑️
        uses: actions/checkout@v4
      - name: ✅ Старт Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: ⏱ Обновление README.md
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.skat59.ru/rss.xml"
          readme_path: "./README.md"
          max_post_count: 40
          commit_message: 💯 Обновление ссылок на новости, продукты, видео ... в README
          committer_username: ProjectSoft-STUDIONIONS
          committer_email: projectsoft2009@yandex.ru
